# Generated by Django 3.0.8 on 2020-12-04 10:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201203_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('idB', models.AutoField(primary_key=True, serialize=False)),
                ('bid', models.FloatField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('id_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingid', to='auctions.Listing')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbidid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
