# Generated by Django 3.0.8 on 2020-12-10 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201204_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('idCo', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('id_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingCommentid', to='auctions.Listing')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCommentid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
